# Generated by Django 3.1 on 2020-09-04 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0002_auto_20200904_0147'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_id',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
