# Generated by Django 3.1 on 2020-09-04 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0006_auto_20200904_0258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='customer_id',
        ),
    ]
