# Generated by Django 3.1 on 2020-09-04 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0008_auto_20200904_0301'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='balance',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='account',
            name='status',
            field=models.CharField(choices=[('0', 'CLOSED'), ('1', 'OPEN')], default='1', max_length=50),
        ),
    ]
